apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-grcs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-grcs
    app.kubernetes.io/part-of: tkrw-pr712-0075-0036-app
  name: devfile-sample-grcs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-grcs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-grcs
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-grcs@sha256:622a21f2691463333f4d9b385fd8c7be6ef30ce920a8685e76d7bbcac23c1fdc
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
